### ISSUE TITLE
TypeError: rescale() got an unexpected keyword argument 'multichannel'

### ISSUE THREAD

**Issue by sivajyothi1** [baumgach/acdc_segmenter#6]
(py34) sivajyothi@PC243-52U:~/acdc_segmenter$ python train.py
2019-02-18 13:58:42,026 Could not import opencv. Augmentation functions will be unavailable.
2019-02-18 13:58:44,241 !! No GPU setup defined. Perhaps you need to set CUDA_VISIBLE_DEVICES etc...?
2019-02-18 13:58:44,241 Could not find cv2. If you want to use augmentation function you need to setup OpenCV.
2019-02-18 13:58:44,241 EXPERIMENT NAME: unet3D_bn_modified_wxent_tfbn
2019-02-18 13:58:44,241 This configuration of mode, size and target resolution has not yet been preprocessed
2019-02-18 13:58:44,241 Preprocessing now!
2019-02-18 13:58:44,242 Counting files and parsing meta data...
2019-02-18 13:58:44,336 Parsing image files
2019-02-18 13:58:44,336 -----------------------------------------------------------
2019-02-18 13:58:44,336 Doing: /home/sivajyothi/acdc_segmenter/data/training/patient035/patient035_frame01.nii.gz
2019-02-18 13:58:44,355 Pixel size:
2019-02-18 13:58:44,355 (1.67969, 1.67969, 5.0)
Traceback (most recent call last):
  File "train.py", line 528, in <module>
    main()
  File "train.py", line 518, in main
    run_training(continue_run)
  File "train.py", line 79, in run_training
    split_test_train=(not train_on_all_data)
  File "/home/sivajyothi/acdc_segmenter/acdc_data.py", line 365, in load_and_maybe_process_data
    prepare_data(input_folder, data_file_path, mode, size, target_resolution, split_test_train=split_test_train)
  File "/home/sivajyothi/acdc_segmenter/acdc_data.py", line 203, in prepare_data
    mode='constant')
TypeError: rescale() got an unexpected keyword argument 'multichannel'

---- Can you please help me to resolve this issue???
Ubuntu - 18.04

**Comment by baumgach** [comment]
At the time of publishing this code this feature was only available in the bleeding edge version of scikit-image. Perhaps, now it has been integrated into the normal releases. I am not sure. Have you installed all the requirements according to the requirements.txt file? In particular:

pip install -e git+https://github.com/scikit-image/scikit-image/#egg=scikit-image

Let me know if this fixes the problem?

**Comment by sivajyothi1** [comment]
pip install -e git+https://github.com/scikit-image/scikit-image/#egg=scikit-image
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Obtaining scikit-image from git+https://github.com/scikit-image/scikit-image/#egg=scikit-image
  Updating ./src/scikit-image clone
    Complete output from command python setup.py egg_info:
    Python 3.4.5 detected.
    
    scikit-image 0.15+ support only Python 3.5 and above.
    
    For Python 2.7, please install the 0.14.x Long Term Support using:
    
     $ pip install 'scikit-image<0.15'
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/sivajyothi/acdc_segmenter/src/scikit-image/

--- yes, i installed all the requirements mentioned in requirements.txt
while installing scikit-image i got the error as mentioned above, that'swhy i installed scikit-image version 0.12.3 using the command 'pip install scikit-image==0.12.3'

**Comment by baumgach** [comment]
Okay I see, their bleeding edge version is no longer compatible with python 3.5. I checked and I am successfully running the code with scikit-image==0.14.0. Could you give it a go, please? If it works I will update the dependencies.

**Comment by sivajyothi1** [comment]
(py34) sivajyothi@PC243-52U:~/acdc_segmenter$ python train.py
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    import image_utils
  File "/home/sivajyothi/acdc_segmenter/image_utils.py", line 6, in <module>
    from skimage import measure
  File "/home/sivajyothi/anaconda3/envs/py34/lib/python3.4/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/home/sivajyothi/anaconda3/envs/py34/lib/python3.4/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/home/sivajyothi/anaconda3/envs/py34/lib/python3.4/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'


---- i installed scikit-image==0.14.0 now. Now i'm getting different error.

**Comment by baumgach** [comment]
Hello, because support for Python 3.4 is ending soon I upgraded all the dependencies for Python 3.5 and tensorflow 1.12 while I was at it. I pasted my pip freeze into the requirements.txt file. This exact configuration works for me now. Could you please confirm that it works for you as well? Best wishes, Christian

**Comment by sivajyothi1** [comment]
Hello, it worked for me when i used python 3.5 environment. Nice work.
Thank you.

**Comment by Dopamine-TX** [comment]
you can aslo change multichanel to channel_axits

**Comment by Kirstihly** [comment]
> you can aslo change multichanel to channel_axits

setting ```channel_axis=-1``` works for color images

(I'm using conda environment ```python=3.9```, ```scikit-image==0.20.0```)
